#log-path = "./logs"
# http-port = 80
url-path = ""

# gtoken配置文件
[gtoken]
    # 缓存模式 1 gcache 2 gredis
    cache-mode = 1
    # 是否支持多端登录
    multi-login = true

[server]
    Address          = ":80"
    ServerRoot       = "public"
    LogPath          = "./logs"
#    IndexFiles       = ["index.php", "main.php"]
    AccessLogEnabled = false
    ErrorLogEnabled  = true
    PProfEnabled     = true
#    SessionIdName    = "MySessionId"
#    SessionPath      = "/tmp/MySessionStoragePath"
#    SessionMaxAge    = "24h"
#    DumpRouterMap    = false

# 全局日志配置
[logger]
    Path   = "./logs"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
#    Path        = "./template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "admin"
    pass = "123"

# 数据库配置
[database]
    link = "mysql:root:A123456@tcp(127.0.0.1:13306)/gmanager"

# 工具相关配置
[gfcli]
    # 工具编译配置
    [gfcli.build]
        name     = "gmanager"
        arch     = "amd64"
        system   = "linux,windows"
        pack     = "public,template"
        mod      = ""
        cgo      = 0

    # dao生成
    [[gfcli.gen.dao]]
        link         = "mysql:root:A123456@tcp(127.0.0.1:13306)/gmanager"
        removePrefix = "sys_"
        tables       = "sys_config,sys_department,sys_log,sys_menu,sys_role,sys_role_menu,sys_user,sys_user_role"